# This is a test file generated by hipRAND for install time.
# It differs slightly from the default testfile, and you may encounter issues because of that.
add_test(test_hiprand_api "../test_hiprand_api")
add_test(test_hiprand_cpp_wrapper "../test_hiprand_cpp_wrapper")
add_test(test_hiprand_kernel "../test_hiprand_kernel")
add_test(test_hiprand_linkage "../test_hiprand_linkage")
